project:
  type: book

website:
  site-url: https://jhleakakos.github.io/statsbook

book:
  title: "statsbook"
  author: "Joseph Leakakos"
  date: "2/10/2026"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - slate
